### ISSUE TITLE
Solve-Function

### ISSUE THREAD

**Issue by ronnycsharp** [sys27/xFunc#154] opened 2016-10-27 07:46 UTC
Hi Dimitry,

I will add a few nice to have features here.
Maybe we can implement it together.

For example a simple linear equation solver.
Like 2x+4=12, or a 2x^2+4=12, x= ...

Regards
Ronny

**Comment by sys27** [comment] 2016-10-27 10:26
Duplicate of #39.

**Comment by sys27** [comment] 2016-10-27 10:28
Right now, the priority is to complex the work on complex number and fix existing bugs.

Also, I don't know a good solution for it (to support any kind of equation at the same time).

**Closed** 2017-02-18 15:31 UTC
Labels: duplicate
